"""Envelope encryption for integration credentials (§20).

Secrets (WordPress application passwords, API keys, OAuth refresh tokens…)
are encrypted with Fernet (AES-128-CBC + HMAC-SHA256) before they touch the
database, so a leaked DB dump or a Turso snapshot never exposes plaintext.

The key comes from the environment only:

    ENCRYPTION_KEY=<44-char urlsafe base64>     # generated by `new_key()`

If ENCRYPTION_KEY is missing we refuse to store secrets rather than silently
saving them in the clear — reads of already-stored rows still work as long as
the original key is present.
"""
from __future__ import annotations

import base64
import hashlib
import os

from app.logging_config import get_logger

log = get_logger("integrations.crypto")

try:  # cryptography is a hard dependency in requirements.txt
    from cryptography.fernet import Fernet, InvalidToken
    _HAVE_FERNET = True
except Exception:  # noqa: BLE001 — keep the app importable without it
    Fernet = None  # type: ignore[assignment]
    InvalidToken = Exception  # type: ignore[assignment]
    _HAVE_FERNET = False

PREFIX = "fernet:"


class CryptoError(RuntimeError):
    """Raised when a secret cannot be encrypted or decrypted."""


def new_key() -> str:
    """Generate a fresh key. Use once, then store it in the environment."""
    if not _HAVE_FERNET:
        raise CryptoError("cryptography is not installed")
    return Fernet.generate_key().decode()


def _normalise_key(raw: str) -> bytes:
    """Accept either a real Fernet key or any passphrase.

    A passphrase is stretched with SHA-256 so a human-typed value still yields
    a valid 32-byte key — convenient, but a generated key is preferred.
    """
    raw = raw.strip()
    try:
        if len(base64.urlsafe_b64decode(raw.encode())) == 32:
            return raw.encode()
    except Exception:  # noqa: BLE001 — not a base64 key, treat as passphrase
        pass
    digest = hashlib.sha256(raw.encode("utf-8")).digest()
    return base64.urlsafe_b64encode(digest)


def _cipher():
    key = os.environ.get("ENCRYPTION_KEY", "").strip()
    if not key:
        return None
    if not _HAVE_FERNET:
        raise CryptoError("cryptography is not installed — cannot handle secrets")
    return Fernet(_normalise_key(key))


def is_configured() -> bool:
    """True when the server is able to store new secrets."""
    return bool(os.environ.get("ENCRYPTION_KEY", "").strip()) and _HAVE_FERNET


def encrypt(plaintext: str) -> str:
    cipher = _cipher()
    if cipher is None:
        raise CryptoError(
            "ENCRYPTION_KEY تنظیم نشده است؛ برای امنیت، ذخیره‌ی Secret انجام نشد."
        )
    return PREFIX + cipher.encrypt(plaintext.encode("utf-8")).decode()


def decrypt(ciphertext: str) -> str:
    if not ciphertext:
        return ""
    if not ciphertext.startswith(PREFIX):
        # Legacy/plaintext value — return as-is so old rows keep working.
        return ciphertext
    cipher = _cipher()
    if cipher is None:
        raise CryptoError("ENCRYPTION_KEY تنظیم نشده است؛ رمزگشایی ممکن نیست.")
    try:
        return cipher.decrypt(ciphertext[len(PREFIX):].encode()).decode("utf-8")
    except InvalidToken as exc:  # wrong/rotated key
        raise CryptoError(
            "رمزگشایی ناموفق بود — احتمالاً ENCRYPTION_KEY عوض شده است."
        ) from exc


def mask(value: str, keep: int = 4) -> str:
    """Render a secret for display: only the last few characters survive."""
    if not value:
        return ""
    if len(value) <= keep:
        return "•" * len(value)
    return "•" * max(4, len(value) - keep) + value[-keep:]
